---
language: python
before_install:
  - npm install stylus@0.27.2
install:
  - pip install coveralls
python:
  - "3.3"

# --source specifies what packages to cover, you probably want to use that option
script:
    coverage run --source={{ cookiecutter.project_name }} setup.py test

after_success: coveralls
